INSERT INTO users (nombre,email) VALUES ('Walter','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Pedrito','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Mariano','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Juan','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Rocio','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Maria','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Beto','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Pepe','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Lauti','mail@gmail.com')
INSERT INTO users (nombre,email) VALUES ('Diego','mail@gmail.com')


INSERT INTO categorias (descripcion) VALUES ('Musica')
INSERT INTO categorias (descripcion) VALUES ('Peliculas')
INSERT INTO categorias (descripcion) VALUES ('Deportes')
INSERT INTO categorias (descripcion) VALUES ('Construccion')
INSERT INTO categorias (descripcion) VALUES ('Autos')
INSERT INTO categorias (descripcion) VALUES ('Perros')
INSERT INTO categorias (descripcion) VALUES ('Aviones')
INSERT INTO categorias (descripcion) VALUES ('Programacion')
INSERT INTO categorias (descripcion) VALUES ('Diseno')
INSERT INTO categorias (descripcion) VALUES ('Arte')

INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('lalala','11/15/2021',1,1)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Rock','11/15/2021',0,2)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Ford','11/15/2021',1,3)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Avengers','11/15/2021',0,4)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Ladrillos','11/15/2021',0,5)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Caniche','11/15/2021',1,6)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Boeing','11/15/2021',1,7)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('Javascript','11/15/2021',1,8)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('AdobexD','11/15/2021',1,9)
INSERT INTO notes (title,creation_date,delete_note,id_user) VALUES ('DaVinci','11/15/2021',1,10)


INSERT INTO notexcategoria (id_note,id_categoria) VALUES (1,2)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (2,3)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (3,4)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (4,5)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (5,6)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (6,7)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (7,8)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (8,9)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (9,10)
INSERT INTO notexcategoria (id_note,id_categoria) VALUES (10,1)